{{- $secret := lookup "v1" "Secret" .Values.certsSecretRef.namespace .Values.certsSecretRef.name }}
{{- $apiVersion := split "/" .Values.global.compositionApiVersion -}}
{{- $fullName := printf "finops-webhook-%s-%s" .Values.global.compositionResource $apiVersion._1 -}}
{{- $name := $fullName | trunc 63 | trimSuffix "-" -}}
{{- $webhookFullname := printf "finops.krateo.webhook.%s.%s" .Values.global.compositionResource $apiVersion._1 -}}
{{- $webhookName := $webhookFullname | trunc 63 | trimSuffix "-" | trimSuffix "." -}}
{{- $webhook := lookup (include "finops-webhook-template-chart.admissionregistrationApiVersion" .) "MutatingWebhookConfiguration" "" $name }}
{{- if not $webhook }}
apiVersion: {{ include "finops-webhook-template-chart.admissionregistrationApiVersion" . }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ $name }}
  {{- if .Values.annotations }}
  annotations:
    helm.sh/resource-policy: keep
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "finops-webhook-template-chart.labels" . | nindent 4 }}
webhooks:
  - name: {{ $webhookName }}
    admissionReviewVersions: ["v1", "v1beta1"]
    {{- with .Values.namespaceSelector }}
    namespaceSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    failurePolicy: Ignore
    rules:
      - operations:
        - "UPDATE"
        apiGroups:
        - {{ $apiVersion._0 }}
        apiVersions:
        - {{ $apiVersion._1 }}
        resources:
        - {{ .Values.global.compositionResource }}
        scope: "Namespaced"
    clientConfig:
      {{- if .Values.useHttps }}
      {{- if .Values.generatedCerts }}
      {{- if and $secret $secret.data.caBundle }}
      caBundle: {{ $secret.data.caBundle }}
      {{- else }}
      caBundle: {{ b64enc .Values.CA }}
      {{- end}}
      {{- end }}
      {{- end }}
      service:
        name: {{ .Values.service.name }}
        namespace: {{ .Values.service.namespace }}
        port: {{ .Values.service.port }}
    sideEffects: None
    {{- if .Values.timeoutSeconds }}
    timeoutSeconds: {{ .Values.timeoutSeconds }}
    {{- end }}
{{- end }}